Track screens explicitly in Firebase
segmentio/analytics-ios-integrations pull request #11
Opened 2020-01-22 11:41 UTC by stianjensen

This will allow explicitly tracked screens in analytics-react-native using `analytics.screen` to actually be tracked in Firebase.

2020-01-28 01:24 UTC, CarlosMecha requested changes
Hi! Thank you so much for submitting the chnage. Would be possible to add unitests too?

2020-01-28 12:58 UTC, stianjensen commented
I added a test now! Is that good, or is there something more specific I should test for?

As far as I can see, Firebase doesn't take any extra properties or anything for its screen tracking method, so I don't think adding any specific properties, contexts would do anything at least.

2020-02-14 00:55 UTC, briemcnally approved these changes

2020-02-14 01:23 UTC, merged

2020-02-14 01:30 UTC, briemcnally commented
hey @stianjensen I am releasing this on our legacy Firebase repo: https://github.com/segment-integrations/analytics-ios-integration-firebase/pull/48. This iOS monorepo is still a work in progress and not yet adequately ready for contributions/releases. I will be releasing version 1.6.0 momentarily. Thanks for your contribution :)